#ifndef FALURE_CODES_H
#define FALURE_CODES_H

enum failure_codes {
	SUCCESS_NO_FAILURE,
	INSUFFICENT_ARGS_FAILURE,
	FORK_FAILURE,
	CHILD_EXEC_FALIURE,
	PTRACE_ATTACHMENT_FAILURE,
	PTRACE_OPTIONS_TRACESYSGOOD_FAILURE,
	CHILD_WAIT_FAILURE,
	PTRACE_CONTINUE_FAILURE,
	REGISTER_VALUE_RETRIEVAL_FAILURE,
};

#endif